### ISSUE TITLE
Convention for specifying related ID in belongs-to relation

### ISSUE THREAD

**Issue by crishoj** [m1212e/prismabox#8]
Example schema with a belongs-to relation:

```prisma
model Item {
  id         Int      @id @default(autoincrement())
  name       String
  categoryId Int
  category   Category @relation(fields: [categoryId], references: [id])
}

model Category {
  id   Int    @id @default(autoincrement())
  name String @unique
  Item Item[]
}
```

I would expect the generated `ItemInputCreate` to include `name` and `categoryId` fields, but it appears that `categoryId` is wrapped in a struct in `ItemRelationsInputCreate`:

```ts
export const ItemRelationsInputCreate = t.Object(
  {
    category: t.Object(
      {
        connect: t.Object(
          {
            id: t.String({ additionalProperties: false }),
          },
          { additionalProperties: false },
        ),
      },
      { additionalProperties: false },
    ),
  },
  { additionalProperties: false },
);
```

Contrary to my expectation, `{name: "Foo", categoryId: 1}` is not valid input for creating an `Item`. Is this intentional?

**Comment by m1212e** [comment]
Hey, thanks for reporting. What you experience is indeed a bug which I fixed in the latest release, please make sure to bump the version! But it might not be the bug you were expecting.

**What was the problem?**
The connect object in the input relation schema just assumed that every other model will have a "String" as a primary id type. But in you example it is a number which causes a mismatch when passing the objects into prisma.

**How is it fixed?**
Int, BigInt and String are now supported types for IDs in connect schemes.

**How does your code work/An example on how to use your models:**
```ts
import { PrismaClient } from "@prisma/client";
import { Type, type Static } from "@sinclair/typebox";
import {
	ItemRelationsInputCreate,
	ItemPlainInput,
} from "../prisma/generated/schema/Item";

const db = new PrismaClient();

// All we need for a creation: The relations and the plain fields
const CreationSchema = Type.Composite([
	ItemRelationsInputCreate,
	ItemPlainInput,
]);

// This is how an instanciated object matching our schema could look like
const r: Static<typeof CreationSchema> = {
	name: "test", // we provide a name from the ItemPlainInput schema
	category: {
		connect: {
			id: 1, // and connect the about to create entity with an already existing entity by using the fields required in the ItemRelationsInputCreate schema
		},
	},
};

// we can pass it into prisma
db.item.create({ data: r });
// doing it manually would look like this
db.item.create({
	data: {
		name: "adawd",
		category: {
			connect: {
				id: 1,
			},
		},
	},
});
```

> Contrary to my expectation, {name: "Foo", categoryId: 1} is not valid input for creating an Item. Is this intentional?
**Yes!** Prismabox is opinionated in how to use relations. It strictly enforces usage of the checked inputs since it is easier for generation and allows for kindof better type safety/better extensibility. If you are unfamiliar with the difference, take a look at the types generated by prisma for your input model creation (This is code generated by prisma):
```ts
  /**
   * Item create
   */
  export type ItemCreateArgs<ExtArgs extends $Extensions.InternalArgs = $Extensions.DefaultArgs> = {
    /**
     * Select specific fields to fetch from the Item
     */
    select?: ItemSelect<ExtArgs> | null
    /**
     * Choose, which related nodes to fetch as well.
     */
    include?: ItemInclude<ExtArgs> | null
    /**
     * The data needed to create a Item.
     */
    data: XOR<ItemCreateInput, ItemUncheckedCreateInput> // <-- see here, you can use the normal or unchecked version
  }
```
The checked inputs look like this:
```ts
  export type ItemCreateInput = {
    name: string
    category: CategoryCreateNestedOneWithoutItemInput
  }

  export type CategoryCreateNestedOneWithoutItemInput = {
    create?: XOR<CategoryCreateWithoutItemInput, CategoryUncheckedCreateWithoutItemInput>
    connectOrCreate?: CategoryCreateOrConnectWithoutItemInput
    connect?: CategoryWhereUniqueInput
  }

  export type CategoryWhereUniqueInput = Prisma.AtLeast<{
    id?: number
    name?: string
    AND?: CategoryWhereInput | CategoryWhereInput[]
    OR?: CategoryWhereInput[]
    NOT?: CategoryWhereInput | CategoryWhereInput[]
    Item?: ItemListRelationFilter
  }, "id" | "name">
```
While these are the unchecked inputs:
```ts
  export type ItemUncheckedCreateInput = {
    id?: number
    name: string
    categoryId: number
  }
```
In your example you are using the unchecked input which indeed would not work with the generated prismabox schemes. But the generated schemes comply with the required prisma types as you can see in my example, you can pass the right into the creation call!

**Comment by crishoj** [comment]
Thank you for the explanation. 

Although I do see the appeal of checked relation inputs, the format fits poorly with our application.

I am tempted to experiment with either adding a `checkedRelationInput` generator option (default `true`), or generating additional types for unchecked relations:
- `*UncheckedRelationsInputCreate`
- `*UncheckedInputCreate`
- `*UncheckedRelationsInputUpdate`
- `*UncheckedInputUpdate`

**Comment by m1212e** [comment]
I think an additional config option which defaults to false which enables the `Unchecked` model creation would be what I'd do. This way folks like you could just switch to on and have additional models with unchecked input structure generated. Happy to review a PR!

**Comment by m1212e** [comment]
I'll close this for now but feel free to get in contact if you want to work on this!

**Comment by crishoj** [comment]
Just FYI, I ended up converting our app to checked relation inputs. Thanks for making Prismabox!
